version: 2.1

jobs:
  build-linux:
    working_directory: ~/repo
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Required Libraries
          command: |
            sudo apt-get update -y
            sudo apt-get install -y \
              dpkg \
              fakeroot \
              rpm \
              libxtst-dev \
              libx11-dev \
              libxkbfile-dev \
              libpng-dev \
              make \
              gcc \
              g++
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Linux App
          command: npm run build:linux
      - store_artifacts:
          path: dist
          destination: build-artifacts/linux
      - run:
          name: SFTP upload (Linux)
          command: |
            curl -T ./dist/* sftp://$FTP_SERVER/var/www/textwrench.ai/public_html/downloads/linux-files/ --user $FTP_USERNAME:$FTP_PASSWORD --insecure

  build-windows:
    working_directory: ~/repo
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Required Libraries
          command: |
            sudo dpkg --add-architecture i386
            sudo apt-get update -y
            sudo apt-get install -y \
              dpkg \
              fakeroot \
              rpm \
              libxtst-dev \
              libx11-dev \
              libpng-dev \
              make \
              gcc \
              wine \
              wine32 \
              g++
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Windows App
          command: npm run build:win
      - store_artifacts:
          path: dist
          destination: build-artifacts/windows
      - run:
          name: SFTP upload (Windows)
          command: |
            curl -T ./dist/* sftp://$FTP_SERVER/var/www/textwrench.ai/public_html/downloads/windows-files/ --user $FTP_USERNAME:$FTP_PASSWORD --insecure

  build-mac:
    macos:
      xcode: 14.0.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build macOS App
          command: npm run build:mac
      - store_artifacts:
          path: dist
          destination: build-artifacts/mac
      - run:
          name: SFTP upload (macOS)
          command: |
            curl -T ./dist/* sftp://$FTP_SERVER/var/www/textwrench.ai/public_html/downloads/mac-files/ --user $FTP_USERNAME:$FTP_PASSWORD --insecure

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - build-linux
      - build-windows
      # - build-mac
