version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2025.01
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image with SSH
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build --ssh default --build-arg GIT_REPO=git@github.com:a-ahandani/textwrench-app.git -t $DOCKERHUB_USERNAME/tw-build:$TAG .

      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/tw-build:$TAG

      - run:
          name: Run application Docker container with volume mount
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            sudo apt-get update && sudo apt-get install -y sshpass
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker pull $DOCKERHUB_USERNAME/tw-build:$TAG && \
              docker stop tw-build || true && \
              docker rm tw-build || true && \
              docker run --name tw-build -d \
              -e GIT_REPO=git@github.com:a-ahandani/textwrench-app.git \
              -v /var/www/textwrench.ai/downloads:/app/downloads \
              -v \$HOME/.ssh:/root/.ssh \
              $DOCKERHUB_USERNAME/tw-build:$TAG sh -c 'rm -rf /app/downloads/* && npm install && npm run build:win && cp -r /app/dist/* /app/downloads && tail -f /dev/null'"
