export const IPC_EVENTS = {
  SET_STORE_VALUE: 'set-store-value',
  GET_STORE_VALUE: 'get-store-value',
  STORE_CHANGED: 'store-changed',
  WATCH_STORE: 'watch-store',
  LOGIN: 'login',
  LOGOUT: 'logout',
  GET_PROFILE: 'get-profile',
  GET_PROMPTS: 'get-prompts',
  GET_TEMPLATES: 'get-templates',
  GET_CATEGORIES: 'get-categories',
  UPDATE_PROMPT: 'update-prompt',
  DELETE_PROMPT: 'delete-prompt',
  CREATE_PROMPT: 'create-prompt',
  LOGIN_FULFILLED: 'login-fulfilled',
  CLOSE_WINDOW: 'close-window',
  VERIFY_TOKEN: 'verify-token',
  UPDATE_SHORTCUTS: 'update-shortcuts',
  GET_VERSION: 'get-version',
  UPDATE_AVAILABLE: 'update-available',
  UPDATE_PROGRESS: 'update-progress',
  UPDATE_DOWNLOADED: 'update-downloaded',
  QUIT_AND_INSTALL: 'quit-and-install',
  OPEN_MODAL: 'open-modal',
  PROCESS_TEXT: 'process-text',
  PROCESS_TEXT_STREAM_START: 'process-text-stream-start',
  PROCESS_TEXT_STREAM_CHUNK: 'process-text-stream-chunk',
  PROCESS_TEXT_STREAM_DONE: 'process-text-stream-done',
  PROCESS_TEXT_STREAM_ERROR: 'process-text-stream-error',
  PROCESS_TEXT_STREAM_CANCEL: 'process-text-stream-cancel',
  HIDE_PASTE: 'hide-paste',
  SET_SELECTED_TEXT: 'set-selected-text',
  PASTE_TEXT: 'paste-text',
  // Single unified expand event. Renderer sends payload describing panel + desired action.
  TOOLBAR_EXPAND: 'toolbar-expand',
  TOOLBAR_OPEN_PANEL: 'toolbar-open-panel',
  TOOLBAR_RESET_UI: 'toolbar-reset-ui'
}
