name: Update package.json version on tag

on:
  push:
    tags:
      - '*'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Replace with your default branch name (e.g., main, master)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get the tag version
        id: get-tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update package.json version
        run: npm version $TAG_VERSION --no-git-tag-version

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main  # Replace with your default branch name
          git add package.json
          git commit -m "Update package.json version to $TAG_VERSION"
          git push origin main  # Replace with your default branch name
